image: python:2.7-jessie
stages:
  - lint
  - test
before_script:
  - pip install pipenv
  - ./run.sh init

# Any branch
lint:
  stage: lint
  script:
    - ./run.sh lint

test:
  stage: test
  script:
    - ./run.sh unit-test
