image: python:3.7-alpine3.8
stages:
  - lint
  - test
before_script:
  - pip install pipenv

# Any branch
lint:
  stage: lint
  script:
    - ./run.sh lint

test:
  stage: test
  script:
    - ./run.sh init
    - ./run.sh test
